name: Build and deploy Python app to Azure Web App - snapora-web-21722

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Run tests here if you want
      # - name: Run tests
      #   run: |
      #     source venv/bin/activate
      #     python manage.py test

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .  # Upload everything except venv
            !venv

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_69461681DC8F49EA8952362C1015E45E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2FBFE62EA43E41169313353BEFBDFDA6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B8504DC6BA324E6DBCCB48E7991A1A7A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'snapora-web-21722'
          package: './'  # deploy root of downloaded artifact
